### ISSUE TITLE
Remito Entrega

### ISSUE THREAD

**Issue by pkogan** [pkogan/hacedores#2]
Agregar Campo Receptor para Nombre Apellido Cargo e Institución

- [x] -   Index-hacedor (grid entregas)
- [x]    View entrega en 3 formatos
- [x] General Con todos los datos +qr
- [x] público solo lectura
- [x] hacedor solo update/delete compartir link qr. hasta que sea aceptada la entrega
- [x] gestor solo validar compartir link qr.

**Comment by pkogan** [comment]
Se agrega el campo idCiudad a la Entrega y vuelve a ser Allow Null la Institución porque el Otro no nos sirve más cuando agregamos la selección por ciudad.

**Comment by cnngimenez** [comment]
Resuelto en commit 42ab3e77e73c0e7b9bb16e3781a7118ba87550a8.
