### ISSUE TITLE
Importar Instituciones

### ISSUE THREAD

**Issue by pkogan** [pkogan/hacedores#4]

**Comment by cnngimenez** [comment]
Logré filtrar las instituciones de acá: http://datos.salud.gob.ar/dataset/listado-establecimientos-de-salud-asentados-en-el-registro-federal-refes

Estos son lo que corresponden a Neuquén y Río Negro. Tengo una pregunta:

¿No se complicaría buscar una intitución sin un autocompletado o algo similar? :thinking:  Por ahí, usando el `<select>` puede generar un listado muy extenso. ¿Usaríamos algo como [Typeahead.js](http://twitter.github.io/typeahead.js/)?

Luego genero el CSV con los campos para importarlo a la BD.

[listado-establecimientos-salud.csv.gz](https://github.com/pkogan/hacedores/files/4423279/listado-establecimientos-salud.csv.gz)

**Comment by pkogan** [comment]
En Principio Importamos todos pero solo mostramos para selección los de tipología 10 Cuidados Especiales. También le vamos a Agregar a la Entrega la ciudad en donde se realiza la Entrega porque hay casos de que entregan en una ciudad distinta en la que viven. También para que sirva de selección de la Institución sigue en #2

**Comment by pkogan** [comment]
Ya que vamos a seleccionar por Ciudad, habría que importar toda la bbdd de Instituciones.  Que opinas?
- Ejemplo de Patagones - Provincia de Buenos Aires queda en frente de Viedma.

**Comment by pkogan** [comment]
Instituciones que tenían idCiudad Valido importadas en tabla institución 

[institucion.sql.gz](https://github.com/pkogan/hacedores/files/4431500/institucion.sql.gz)
